#!/bin/bash
set -euo pipefail

echo "Inside pre-command hook"

# COUNT=$(find . -name "$PATTERN" | wc -l)

# echo "Found ${COUNT} files matching ${PATTERN}"

# buildkite-agent annotate "Found ${COUNT} files matching ${PATTERN}"

CRITERIA_OUTPUT=$(check criteria output)

echo "Output of Criteria = ${CRITERIA_OUTPUT}"

RESULT=$(send success-result)

echo "Pre-command Result: ${RESULT}"
